---
- name: Ensure we have UFW installed for firewall
  apt:
    name: ufw
    state: present

- name: Deny everything and disable the firewall
  community.general.ufw:
    state: disabled
    policy: deny

- name: Allow connections to port 443 from anywhere
  community.general.ufw:
    rule: allow
    port: 443

- name: Allow connections to SSH and samba ports from LAN IP addresses
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    from: "{{ router_ip }}/24"
  loop:
    - 22
    - 139
    - 445

- name: Enable the firewall
  community.general.ufw:
    state: enabled
...
