- name: Get UID of our user
  command: "id -u"
  register: user_uid

- name: Get GID of our user
  command: "id -u"
  register: user_gid

- name: Ensure our user owns the samba share
  file:
    path: "{{ pnas_share_path }}"
    owner: "{{ pnas_user }}"

- name: Ensure our user owns the navidrome music library
  file:
    path: "{{ pnas_share_path }}"
    owner: "{{ pnas_user }}"

- name: Ensure our user can manage docker containers
  user:
    name: "{{ pnas_user }}"
    append: yes
    groups: docker
  become: yes

- name: Ensure we have a directory for Navidrome data on the host
  file:
    path: MM-PNS/data/navidrome
    state: directory

- name: Copy over Navidrome config
  copy:
    src: navidrome.toml
    dest: MM-PNS/data/navidrome/config.toml

- name: Ensure we have a directory for filebrowser data on the host
  file:
    path: MM-PNS/data/filebrowser
    state: directory

- name: Ensure filebrowser database file exists on the host
  file:
    path: MM-PNS/data/filebrowser/database.db
    state: touch

- name: Copy over filebrowser config
  copy:
    src: filebrowser.json
    dest: MM-PNS/data/filebrowser/filebrowser.json

- name: Copy over SSL certs and config files for nginx
  copy:
    src: nginx
    dest: MM-PNS

- name: Create populated docker-compose.yml file for service initialization
  template:
    src: templates/docker-compose.yml.j2
    dest: MM-PNS/docker-compose.yml
